apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricket-ml
  namespace: cricket-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cricket-ml
  template:
    metadata:
      labels:
        app: cricket-ml
    spec:
      containers:
        - name: cricket-ml
          image: g0u74m/cricket-ml:latest
          ports:
            - containerPort: 5000
