apiVersion: v1
kind: Service
metadata:
  name: cricket-ml-service
  namespace: cricket-ml
spec:
  type: NodePort
  selector:
    app: cricket-ml
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
